SarvamCart/Areas/Admin/Controllers/DashBoardController.cs
using SarvamCart.Domain.Models;
using SarvamCart.Domain.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SarvamCart.Areas.Admin.Controllers
{
    [Authorize(Roles ="admin")]
    public class DashBoardController : Controller
    {
        private readonly IProductService ProductServices;
        private readonly IUserService UserServices;

        public DashBoardController(IProductService _productServices,IUserService _userServices)
        {
            ProductServices = _productServices;
            UserServices = _userServices;
        }

        // GET: Admin/DashBoard
        public ActionResult Index()
        {
            ManageProduct viewModel = new ManageProduct();
            TempData["totalProduct"] = ProductServices.FindBy(x=>x.IsDeleted == false).Count();
            TempData["activeProduct"] = ProductServices.FindBy(x => x.IsActive == true && !x.IsDeleted).Count();
            TempData["totalUser"] = UserServices.FindBy(x => x.IsActive == true && !x.IsDeleted).Count();

            return View();
        }
    }
}

SarvamCart/Areas/Admin/Controllers/ProductController.cs
using Newtonsoft.Json;
using SarvamCart.Custom;
using SarvamCart.Domain.Data;
using SarvamCart.Domain.Models;
using SarvamCart.Domain.Services;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SarvamCart.Areas.Admin.Controllers
{
    [Authorize(Roles = "admin")]
    public class ProductController : Controller
    {
        //private SarvamEntities db = new SarvamEntities();
        private readonly IProductService ProductServices;
        private readonly IProductImageService ProductImageService;
        private readonly ICategoryService CategoryService;

        public ProductController(IProductService _productServices, ProductImageService _ProductImageService, CategoryService _CategoryService)
        {
            ProductServices = _productServices;
            ProductImageService = _ProductImageService;
            CategoryService = _CategoryService;
        }

        // GET: Admin/Product
        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public ActionResult GetProducts()
        {

            // ViewModelProduct viewModel = new ViewModelProduct();

            var result = ProductServices.FindBy(x => x.IsDeleted == false).Select(x => new ViewModelProduct
            {
                Id = x.Id,
                Title = x.Title,
                ProductCode = x.ProductCode,
                Stock = x.Stock,
                IsActive = x.IsActive,
                DisplayHome = x.DisplayHome,
                Image = x.ProductImages.Where(o => o.IsDeleted == false).FirstOrDefault().InnerImages,
                Category = x.CategoryType.CategoryName,

            }).OrderByDescending(x => x.Id).ToList();


            return Json(new { data = result }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Manage(int? Id)
        {
            ManageProduct viewModel = new ManageProduct();
            // viewModel.CategoryTypes = CategoryService.FindBy(x => x.IsDeleted == false && x.IsActive == true).Select(x => new SelectListItem { Text = x.CategoryName, Value = x.Id.ToString() });
            viewModel.CategoryTypes = CategoryService.FindBy(x => x.IsDeleted == false && x.IsActive == true).OrderBy(x => x.DisplayOrder).Select(x => new SelectListItem { Text = x.Id.ToString(), Value = x.CategoryName }).ToList();
            if (Id > 0)
            {
                var result = ProductServices.FirstOrDefault(x => x.Id == Id);
                if (result != null)
                {
                    viewModel.Id = result.Id;
                    viewModel.Title = result.Title;
                    viewModel.Stock = result.Stock;
                    //viewModel.Image = result.Image;
                    viewModel.IsActive = result.IsActive;
                    viewModel.DisplayHome = result.DisplayHome;
                    viewModel.Description = result.Description;
                    viewModel.CategoryTypeId = result.CategoryTypeId;
                    viewModel.Price = result.Price;
                    viewModel.ProductCode = result.ProductCode;
                    viewModel.InnerImage = result.ProductImages?.Where(x => x.IsDeleted == false).Select(x => new ManageProductImages { Id = x.Id, ProductId = x.ProductId, ImageName = x.InnerImages }).ToList();
                }
            }
            return View(viewModel);
        }
        [HttpPost]
        public ActionResult Manage(ManageProduct viewModel, HttpPostedFileBase[] ProductImagespath)
        {
            viewModel.CategoryTypes = CategoryService.FindBy(x => x.IsDeleted == false && x.IsActive == true).OrderBy(x => x.DisplayOrder).Select(x => new SelectListItem { Text = x.CategoryName, Value = x.Id.ToString() });
            string FileName = string.Empty;
            //if (Image != null)
            //{
            //    var newFileName = Guid.NewGuid().ToString() + System.IO.Path.GetExtension(Image.FileName);
            //    string path = Path.Combine(Server.MapPath("~/Assets/UploadedFiles"), newFileName);
            //    Image.SaveAs(path);
            //    FileName = Image.FileName;
            //    viewModel.Image = newFileName;
            //    ViewBag.FileStatus = "File uploaded successfully.";

            //    if (viewModel.Id > 0 && viewModel.Image == null)
            //    {
            //        viewModel.Image = viewModel.Image;
            //    }
            //}
            //else
            //{
            //    ViewBag.FileStatus = "Error while file uploading.";
            //}

            if (ModelState.IsValid)
            {
                var productID = ProductServices.Save(viewModel);
                if (productID > 0)
                {
                    if (ProductImagespath != null)
                    {
                        foreach (var item in ProductImagespath)
                        {
                            var newFileName = Guid.NewGuid().ToString() + System.IO.Path.GetExtension(item.FileName);
                            FileName = Path.GetExtension(item.FileName);
                            FileName = Path.GetFileName(item.FileName);
                            string path = Server.MapPath("~/Assets/UploadedFiles");
                            string ImagePath = Path.Combine(path, newFileName);
                            item.SaveAs(ImagePath);
                            ProductImageService.Add(new ProductImage { ProductId = productID, InnerImages = newFileName });
                        }
                        ProductImageService.Save();
                    }
                }
                return Json(new { result = "Redirect", url = Url.Action("Index", "Product") });
            }
            return View(viewModel);
        }

        [HttpPost]
        public ActionResult Delete(int Id)
        {
            ProductServices.Delete(Id);
            return Json(new { IsSuccess = true });
        }
       
        [HttpPost]
        public ActionResult DeleteImage(int Id)
        {
            ProductImageService.Delete(Id);
            return Json(new { Success = true });
        }
        
        [HttpPost]
        public ActionResult UpdateIsActive(int Id, bool IsActive)
        {
            var data = ProductServices.FirstOrDefault(x => x.Id == Id);
            if (data != null)
            {
                data.IsActive = IsActive;
                if (IsActive == false)
                {
                    data.DisplayHome = false;
                }

                ProductServices.Edit(data);
                ProductServices.Save();
            }
            return Json(new { IsSuccess = true });
        }
    }
}

SarvamCart/Views/Shared/_Categories.cshtml
<ul id="dropdown-user">
    <li><a href="/Home/Product/0" data-id="0" class="myLink">All </a></li>

    @if (ViewBag.category != null)
    {
        foreach (var item in ViewBag.category)
        {
            <li><a href="/Home/Product/@item.Id" data-id="@item.Id" class="myLink">@item.CategoryName</a></li>
        }
    }
</ul>

SarvamCart/Views/Shared/_Layout.cshtml
@{
    var curretLink = ViewContext.RouteData.Values["Controller"].ToString();
    var curretActionLink = ViewContext.RouteData.Values["Action"].ToString();
    var count = @HttpContext.Current.Session["SessionCartCounter"];

}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    @*@Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")*@
    <title>Sarvam - @ViewData["Title"]</title>
    <link rel="apple-touch-icon" sizes="57x57" href="~/Assets/favicon/apple-icon-57x57.png">
    <link rel="apple-touch-icon" sizes="60x60" href="~/Assets/favicon/apple-icon-60x60.png">
    <link rel="apple-touch-icon" sizes="72x72" href="~/Assets/favicon/apple-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="76x76" href="~/Assets/favicon/apple-icon-76x76.png">
    <link rel="apple-touch-icon" sizes="120x120" href="~/Assets/favicon/apple-icon-120x120.png">
    <link rel="apple-touch-icon" sizes="144x144" href="~/Assets/favicon/apple-icon-144x144.png">
    <link rel="apple-touch-icon" sizes="114x114" href="~/Assets/favicon/apple-icon-114x114.png">
    <link rel="apple-touch-icon" sizes="152x152" href="~/Assets/favicon/apple-icon-152x152.png">
    <link rel="apple-touch-icon" sizes="180x180" href="~/Assets/favicon/apple-icon-180x180.png">
    <link rel="icon" type="image/png" sizes="192x192" href="~/Assets/favicon/android-icon-192x192.png">
    <link rel="icon" type="image/png" sizes="32x32" href="~/Assets/favicon/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="96x96" href="~/Assets/favicon/favicon-96x96.png">
    <link rel="icon" type="image/png" sizes="16x16" href="~/Assets/favicon/favicon-16x16.png">
    <link rel="manifest" href="~/Assets/favicon/manifest.json">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="~/Assets/favicon/ms-icon-144x144.png">
    <meta name="theme-color" content="#ffffff">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Sarvam Cart</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="~/Assets/css/animate.min.css">
    <link rel="stylesheet" type="text/css" href="~/Assets/css/megamenu.css">
    <link rel="stylesheet" type="text/css" href="~/Assets/css/style.css">
    <link href="~/Assets/Admin/vendor/libs/toastr/toastr.css" rel="stylesheet" />
</head>
<body>
    <div id="preloader">
        <div id="status">&nbsp;</div>
    </div>
    <header class="header_area header-border-bottom">
        <div class="main_header_area animated">
            <div class="container">
                <nav id="navigation1" class="navigation">
                    <div class="nav-header">
                        <a class="nav-brand" href="@Url.Action("Index", "Home")"><img src="~/Assets/images/logo.png" alt="logo" /></a>
                        <div class="nav-toggle"></div>
                    </div>
                    <div class="nav-menus-wrapper">
                        <ul class="nav-menu align-to-right">
                            <li class="@(curretLink == "Home" && curretActionLink == "Index" ? "active" : "")"><a href="@Url.Action("Index", "Home")">Home</a></li>
                            <li class="@(curretActionLink == "About" ? "active" : "")"><a href="@Url.Action("About", "Home")">About</a></li>
                            <li class="admin-user-dropdown @(curretActionLink == "Product" || curretLink == "ProductDetail" ? "active" : "")">
                                <a href="javascript:;" class="dropdown-toggle">Products</a>
                                @{Html.RenderAction("_Categories", "Home"); }
                            </li>
                            <li class="@(curretActionLink == "Contact" ? "active" : "")"><a href="@Url.Action("Contact", "Home")">Contact Us</a></li>

                            @if (User.Identity.IsAuthenticated && User.IsInRole("User"))
                            {
                                var df = Convert.ToBoolean(count);
                                <li class="">
                                    <a href="@Url.Action("CartList", "UserCart")" style="position:relative;">
                                        <i class="fa fa-shopping-cart"></i>
                                            <span class='badge badge-warning' id='lblCartCount' style="position:absolute;top:20%;"> @count </span>
                                    </a>
                                </li>
                            }

                            @*<li class=""><a href="@Url.Action("WishList","Home")"><i class="fa fa-heart-o"></i> </a></li>*@
                            @if (User.Identity.IsAuthenticated)
                            {
                                <li class="nav-item dropdown">
                                    @if (User.Identity.Name == "admin")
                                    {
                                        <a href="@Url.Action("Index","DashBoard",new { area="Admin"} )">
                                            @User.Identity.Name
                                        </a>
                                    }
                                    else
                                    {
                                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                            @User.Identity.Name
                                        </a>
                                    }
                                    <div class="dropdown-menu text-center logout-dropdown" aria-labelledby="navbarDropdown">
                                        <a href="@Url.Action("LogOut","Account")"><i class="fa fa-sign-out pr-2"></i>LogOut</a>

                                    </div>
                                </li>
                                @*<a href="javascript:;" class="dropdown-toggle">@User.Identity.Name</a>
                                    <li class="@(curretActionLink=="LogOut"?"active":"")"><a href="@Url.Action("LogOut","Account")">LogOut</a></li>*@
                            }
                            else
                            {
                                <li class="@(curretActionLink=="Login"?"active":"")"><a href="@Url.Action("Login","Account")">Login</a></li>
                            }
                        </ul>
                    </div>
                </nav>
            </div>
        </div>
    </header>

    <div class="body-content">
        @RenderBody()
    </div>

    <footer>
        <div class="footer-bg">
            <div class="container">
                <div class="row">
                    <div class="col-md-4 text-sm-center text-md-left">
                        <div class="footer-content">
                            <img src="~/Assets/images/footer-logo.png" />
                            <p>
                                Copyright © 2021 - Sarvam. All Rights Reserved.
                            </p>
                        </div>
                    </div>
                    <div class="col-4 col-sm-3 col-md-2">
                        <div class="footer-menu">
                            <ul class="list-unstyled">
                                <li>
                                    <a href="@Url.Action("Index","Home")">HOME</a>
                                </li>
                                <li>
                                    <a href="@Url.Action("About","Home")">ABOUT US</a>
                                </li>
                                @*<li>
                                        <a href="@Url.Action("Product","Home")">PRODUCTS</a>
                                    </li>
                                    <li>
                                        <a href="@Url.Action("Contact","Home")">CONTACT US</a>
                                    </li>*@
                            </ul>
                        </div>
                    </div>
                    <div class="col-4 col-sm-3 col-md-2">
                        <div class="footer-menu">
                            <ul class="list-unstyled">
                                <li>
                                    <a href="@Url.Action("Index","Home")">PRODUCTS</a>
                                </li>
                                <li>
                                    <a href="@Url.Action("Contact","Home")">CONTACT US</a>
                                </li>
                                @*<li>
                                        <a href="#">KITCHENWARE</a>
                                    </li>
                                    <li>
                                        <a href="#">WATCHES</a>
                                    </li>
                                    <li>
                                        <a href="#">WALLET</a>
                                    </li>
                                    <li>
                                        <a href="#">TRADITIONAL</a>
                                    </li>
                                    <li>
                                        <a href="#">TORAN</a>
                                    </li>*@
                            </ul>
                        </div>
                    </div>
                    <div class="col-sm-6 col-md-4">
                        <div class="footer-contact">
                            <h5>CALL US :</h5>
                            <span>+91 94085 58818</span>
                            <p>
                                Address : G-28, Anupam Business Hub, Yogi Chowk, Gujarat, Surat - 395006, India.
                            </p>
                            <a href="#" class="social-link"><i class="fa fa-facebook-f"></i></a>
                            <a href="#" class="social-link mx-2"><i class="fa fa-twitter"></i></a>
                            <a href="#" class="social-link"><i class="fa fa-instagram"></i></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </footer>

    @*@Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")
        @RenderSection("scripts", required: false)*@
    <script type="text/javascript" src="~/Assets/js/jquery-3.4.1.js"></script>
    <script type="text/javascript" src="~/Assets/js/popper.min.js"></script>
    <script type="text/javascript" src="~/Assets/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="~/Assets/js/megamenu.js"></script>
    <script type="text/javascript" src="~/Assets/js/wow.min.js"></script>
    <script type="text/javascript" src="~/Assets/js/thumbelina.js"></script>
    <script type="text/javascript" src="~/Assets/js/common.js"></script>
    <script src="~/Assets/Admin/vendor/libs/toastr/toastr.js"></script>

    @RenderSection("Scripts", required: false)
    <script>
        $(document).on('click', ".admin-user-dropdown", function () {
            if ($("#dropdown-user").css("display") == "none") {
                $("#dropdown-user").css({ "display": "block", "animation": "0.5s pulse" });
            }
            else {
                $("#dropdown-user").css({ "display": "none", "animation": "0.5s pulse" });
            }
        });
        var route = window.location.href;
        var id = route.split("/").pop();
        if (id != "")
            $("ul#dropdown-user").find("li").find("a[data-id=" + id + "]").addClass("active");
        var b = $("#lblCartCount").text().trim();
        if (b==0) {
            $("#lblCartCount").hide();
        }
        else {
            $("#lblCartCount").show();
        }
    </script>
</body>
</html>

SarvamCart/Views/Shared/_Products.cshtml
@model IEnumerable<SarvamCart.Domain.Models.ViewModelProduct>
@foreach (var product in Model)
{
    if (product.Id > 0)
    {
        <div class="col-sm-6 col-md-4 col-xl-3 mb-3">
            <div class="product-box" data-has-more-rows="@ViewBag.HasMoreRows">
                <img src="~/Assets/UploadedFiles/@product.InnerImage[0].InnerImages" value="@product.Id" class="img-responsive" />
                <div class="overlay">
                    <div class="wish-list-icon">
                        <a href="#"><i class="fa fa-heart"></i></a>
                        <a href="@Url.Action("Index","ProductDetail",new { id=product.Id})"><i class="fa fa-info"></i></a>
                        <a class="cartlnk" data-id="@product.Id"><i class="fa fa-shopping-cart"></i></a>
                    </div>
                </div>
            </div>
            <p class="product-name text-center">@product.Title</p>
            <div class="my--15"></div>
        </div>
    }
    else
    { <div class="col-12 text-center">
            <span class="no-items-message">@ViewBag.Message</span>
        </div>
    }
}

@*@section scripts{
        <script type="text/javascript">
            $(document).ready(function () {
                $(".cartlnk").on("click", function () {
                    debugger;
                    var lnkData = $(this).data();
                    $ajax({
                        type: "POST",
                        url: '@Url.Action("AddToCart", "UserCart")',
                        data: { productId: lnkData.id },
                        success: function (result) {
                            if (result.IsSuccess == true) {
                                window.location.href = "@Url.Action("AddToCart", "UserCart")";
                            }
                        }

                    });
                });
            });


        </script>
    }*@

SarvamCart/Views/Shared/_QuotationPdf.cshtml
@model SarvamCart.Domain.Models.ViewModelQuotaion
@{
    ViewBag.Title = "test";
}
<link href="~/Assets/css/style.css" rel="stylesheet" />
<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">

<div class="container" id="content">
    <div class="company-user-details card-box p-4">
        <div class="row justify-content-between  pb-4">
            <div class="col-xs-7">
                <h4 class="mb-2">From: SarvamCart-Quotation</h4>
                <p class="mb-0">G-28, Anupam Business Hub, Yogi Chowk, </p>
                <p class="mb-0">Surat - 395006, Gujarat, India.</p>
                <p class="mb-0">Call Us: +91 94085 58818</p>
                <p class="mb-0">Email: sarvam.cart123@gmail.com</p>
                <p class="mb-0">Date: @DateTime.Now.ToString("dd/MM/yyyy")</p>
            </div>
            <div class="col-xs-5">
                <h4 class="mb-2">To: @Model.UserName</h4>
                <p class="mb-0">Phone: +91 @Model.ContactNumber</p>
                <p class="mb-0">Email: @Model.UserEmail</p>
                <p class="mb-0">RequestDate: @Model.CreatedOn.ToString("dd/MM/yyyy")</p>
            </div>
        </div>
        <hr>
        <div class="row" id="tblrow">
            <div class="col-12">
                <table class="table-bordered border mx-auto" id="quotation">
                    <thead>
                        <tr>
                            <th>Sr.</th>
                            <th>Product Image</th>
                            <th>Product Code</th>
                            <th style="width:350px;">Product Name</th>
                            <th>Quantity</th>
                            <th>Price</th>
                            <th>Total</th>
                        </tr>
                    </thead>
                    <tbody>
                        @{var count = 0;
                            foreach (var quotationDetail in Model.CartDetails)
                            {
                                var sr = count + 1;
                                <tr>
                                    <td>@sr</td>
                                    <td style="max-width:100px;"><img src="~/Assets/UploadedFiles/@quotationDetail.ProductImage" class="img-fluid" /></td>
                                    <td> <label type="text">@quotationDetail.ProductCode</label> </td>
                                    <td><label type="text">@quotationDetail.ProductName</label></td>
                                    <td><label class="quentity" type="text">@quotationDetail.Quentity</label></td>
                                    <td><label class="finalprice" type="text">@quotationDetail.FinalPrice</label></td>
                                    <td><label class="total" type="number">@(quotationDetail.Quentity * quotationDetail.FinalPrice) </label></td>
                                </tr>
                                count = count + 1;
                            }
                        }
                        <tr>
                            <th colspan="6" class="text-left">Grand Total</th>
                            <td><label type="text">@Model.GrantTotal</label>/-</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

@section scripts{
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="~/Assets/js/common.js"></script>
}