SarvamCart/Areas/Admin/Controllers/ProductController.cs
using Newtonsoft.Json;
using SarvamCart.Custom;
using SarvamCart.Domain.Data;
using SarvamCart.Domain.Models;
using SarvamCart.Domain.Services;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SarvamCart.Areas.Admin.Controllers
{
    [Authorize(Roles = "admin")]
    public class ProductController : Controller
    {
        //private SarvamEntities db = new SarvamEntities();
        private readonly IProductService ProductServices;
        private readonly IProductImageService ProductImageService;
        private readonly ICategoryService CategoryService;

        public ProductController(IProductService _productServices, ProductImageService _ProductImageService, CategoryService _CategoryService)
        {
            ProductServices = _productServices;
            ProductImageService = _ProductImageService;
            CategoryService = _CategoryService;
        }

        // GET: Admin/Product
        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public ActionResult GetProducts()
        {

            // ViewModelProduct viewModel = new ViewModelProduct();

            var result = ProductServices.FindBy(x => x.IsDeleted == false).Select(x => new ViewModelProduct
            {
                Id = x.Id,
                Title = x.Title,
                ProductCode = x.ProductCode,
                Stock = x.Stock,
                IsActive = x.IsActive,
                DisplayHome = x.DisplayHome,
                Image = x.ProductImages.Where(o => o.IsDeleted == false).FirstOrDefault().InnerImages,
                Category = x.CategoryType.CategoryName,

            }).OrderByDescending(x => x.Id).ToList();


            return Json(new { data = result }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Manage(int? Id)
        {
            ManageProduct viewModel = new ManageProduct();
            // viewModel.CategoryTypes = CategoryService.FindBy(x => x.IsDeleted == false && x.IsActive == true).Select(x => new SelectListItem { Text = x.CategoryName, Value = x.Id.ToString() });
            viewModel.CategoryTypes = CategoryService.FindBy(x => x.IsDeleted == false && x.IsActive == true).OrderBy(x => x.DisplayOrder).Select(x => new SelectListItem { Text = x.Id.ToString(), Value = x.CategoryName }).ToList();
            if (Id > 0)
            {
                var result = ProductServices.FirstOrDefault(x => x.Id == Id);
                if (result != null)
                {
                    viewModel.Id = result.Id;
                    viewModel.Title = result.Title;
                    viewModel.Stock = result.Stock;
                    //viewModel.Image = result.Image;
                    viewModel.IsActive = result.IsActive;
                    viewModel.DisplayHome = result.DisplayHome;
                    viewModel.Description = result.Description;
                    viewModel.CategoryTypeId = result.CategoryTypeId;
                    viewModel.Price = result.Price;
                    viewModel.ProductCode = result.ProductCode;
                    viewModel.InnerImage = result.ProductImages?.Where(x => x.IsDeleted == false).Select(x => new ManageProductImages { Id = x.Id, ProductId = x.ProductId, ImageName = x.InnerImages }).ToList();
                }
            }
            return View(viewModel);
        }
        [HttpPost]
        public ActionResult Manage(ManageProduct viewModel, HttpPostedFileBase[] ProductImagespath)
        {
            viewModel.CategoryTypes = CategoryService.FindBy(x => x.IsDeleted == false && x.IsActive == true).OrderBy(x => x.DisplayOrder).Select(x => new SelectListItem { Text = x.CategoryName, Value = x.Id.ToString() });
            string FileName = string.Empty;
            //if (Image != null)
            //{
            //    var newFileName = Guid.NewGuid().ToString() + System.IO.Path.GetExtension(Image.FileName);
            //    string path = Path.Combine(Server.MapPath("~/Assets/UploadedFiles"), newFileName);
            //    Image.SaveAs(path);
            //    FileName = Image.FileName;
            //    viewModel.Image = newFileName;
            //    ViewBag.FileStatus = "File uploaded successfully.";

            //    if (viewModel.Id > 0 && viewModel.Image == null)
            //    {
            //        viewModel.Image = viewModel.Image;
            //    }
            //}
            //else
            //{
            //    ViewBag.FileStatus = "Error while file uploading.";
            //}

            if (ModelState.IsValid)
            {
                var productID = ProductServices.Save(viewModel);
                if (productID > 0)
                {
                    if (ProductImagespath != null)
                    {
                        foreach (var item in ProductImagespath)
                        {
                            var newFileName = Guid.NewGuid().ToString() + System.IO.Path.GetExtension(item.FileName);
                            FileName = Path.GetExtension(item.FileName);
                            FileName = Path.GetFileName(item.FileName);
                            string path = Server.MapPath("~/Assets/UploadedFiles");
                            string ImagePath = Path.Combine(path, newFileName);
                            item.SaveAs(ImagePath);
                            ProductImageService.Add(new ProductImage { ProductId = productID, InnerImages = newFileName });
                        }
                        ProductImageService.Save();
                    }
                }
                return Json(new { result = "Redirect", url = Url.Action("Index", "Product") });
            }
            return View(viewModel);
        }

        [HttpPost]
        public ActionResult Delete(int Id)
        {
            ProductServices.Delete(Id);
            return Json(new { IsSuccess = true });
        }
       
        [HttpPost]
        public ActionResult DeleteImage(int Id)
        {
            ProductImageService.Delete(Id);
            return Json(new { Success = true });
        }
        
        [HttpPost]
        public ActionResult UpdateIsActive(int Id, bool IsActive)
        {
            var data = ProductServices.FirstOrDefault(x => x.Id == Id);
            if (data != null)
            {
                data.IsActive = IsActive;
                if (IsActive == false)
                {
                    data.DisplayHome = false;
                }

                ProductServices.Edit(data);
                ProductServices.Save();
            }
            return Json(new { IsSuccess = true });
        }
    }
}

SarvamCart/Controllers/HomeController.cs
using SarvamCart.Domain.Data;
using SarvamCart.Domain.Models;
using SarvamCart.Domain.Services;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SarvamCart.Controllers
{
    public class HomeController : Controller
    {
        private SarvamEntities db = new SarvamEntities();
        private readonly IProductService ManageProductServices;
        private readonly ICategoryService ManageCategoryServices;
        private readonly IContactUsService ContactUsServices;
        private readonly IQuotationService QuotationService;
        private readonly IMailService MailServices;

        public HomeController(IProductService _manageProductService, IQuotationService _quotationServices, ICategoryService _manageCategoryServices, IContactUsService _contactUsServices, IMailService _mailServices)
        {
            ManageProductServices = _manageProductService;
            ManageCategoryServices = _manageCategoryServices;
            ContactUsServices = _contactUsServices;
            QuotationService = _quotationServices;
            MailServices = _mailServices;
        }
        public ActionResult Index()
        {
            var result = new List<Product>();
            result = ManageProductServices.FindBy(x => x.IsDeleted == false && x.DisplayHome == true).OrderByDescending(o => o.Id).Take(8).ToList();
            if (result.Count() == 0)
            {
                ViewBag.Message = "No Products";
            }
            List<ViewModelProduct> model = new List<ViewModelProduct>();

            foreach (var item in result)
            {
                model.Add(new ViewModelProduct
                {
                    Description = item.Description,
                    Id = item.Id,
                    Title = item.Title,
                    CategoryTypeId = item.CategoryTypeId,
                    IsActive = item.IsActive,
                    ProductCode = item.ProductCode,
                    Stock = item.Stock,
                    DisplayHome = item.DisplayHome,
                    InnerImage = db.ProductImages.Where(x => x.ProductId == item.Id && x.IsDeleted == false).ToList()
                });
            }
            return View(model);
        }

        public ActionResult About()
        {
            return View();
        }

        public ActionResult Contact()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Contact(ContactUsModel viewModel)
        {

            ContactUsServices.Save(viewModel);

            //notify to admin about contact us via email

            var body = viewModel.Message;
            var to = "";
            var from = "";
            var subject = "";
            var html = "";
            to = ConfigurationManager.AppSettings["AdminMailID"];
            from = viewModel.Email;
            subject = "Contact Message";
            html = "<div style='border:1px solid ; width:80%;'><div class='leave' style='margin:0 10% 0 10%;'><p>Name:" + viewModel.Name + "<br>" + "Contact Number:" + viewModel.ContactNumber +
                "<br>" + "Date:" + DateTime.Now +
                      "<p> " + body + "</p>";
            // +"</p><br> <br> " + viewModel.Name + " <br><br></div></div>";
            MailServices.Send(from, to, subject, html);
            if (viewModel != null)
            {
                TempData["Msg"] = "your resquest is send successfully";

            }
            ModelState.Clear();
            return View();
        }

        public ActionResult Product(int id)
        {
            //ManageProduct viewModel = new ManageProduct();
            //var result = new List<Product>();

            //result = ManageProductServices.FindBy(x => x.IsDeleted == false && x.IsActive == true && x.CategoryTypeId == id).OrderByDescending(o => o.Id).Skip(0).Take(6).ToList();
            //if (result.Count() == 0)
            //{
            //    ViewBag.Message = "No Products";
            //}
            //List<ViewModelProduct> model = new List<ViewModelProduct>();

            //foreach (var item in result)
            //{
            //    model.Add(new ViewModelProduct
            //    {
            //        Description = item.Description,
            //        Id = item.Id,
            //        Title = item.Title,
            //        InnerImage = db.ProductImages.Where(x => x.ProductId == item.Id && x.IsDeleted == false).ToList()
            //    });
            //}
            //ViewBag.categoryName = ManageCategoryServices.FindBy(x => x.Id == id).ToList()[0].CategoryName;
            if (id != 0)
            {
                ViewBag.categoryName = ManageCategoryServices.FindBy(x => x.Id == id).FirstOrDefault().CategoryName;
            }
            else
            {
                ViewBag.categoryName = "All";
            }

            //var category = new List<CategoryType>();
            ViewBag.category = ManageCategoryServices.FindBy(x => x.IsActive == true).Where(x => x.IsDeleted == false).ToList();
            ViewBag.CategoryId = id;


            return View();
        }
        public ActionResult _Categories()
        {
            var category = new List<CategoryType>();
            ViewBag.category = ManageCategoryServices.FindBy(x => x.IsActive == true).Where(x => x.IsDeleted == false).OrderBy(o => o.DisplayOrder).ToList();
            return PartialView();
        }

        public ActionResult _Products(int currentPageNo, int categoryId)
        {
            ManageProduct viewModel = new ManageProduct();

            int pageSize = 8;
            int skipRows = currentPageNo * pageSize;
            var products = ManageProductServices.FindBy(x => x.IsDeleted == false && x.IsActive == true && (categoryId == 0 || x.CategoryTypeId == categoryId));
            var totalProducts = products.Count();

            var result = products.OrderByDescending(o => o.Id).Skip(skipRows).Take(pageSize).Select(x =>
            new ViewModelProduct
            {
                Description = x.Description,
                Id = x.Id,
                Title = x.Title,
                InnerImage = x.ProductImages.Where(i => i.IsDeleted == false).ToList()
            }).ToList();

            var totalProductDisplayed = (currentPageNo + 1) * pageSize;
            var hasMoreProducts = totalProductDisplayed < totalProducts;
            ViewBag.HasMoreRows = hasMoreProducts ? "true" : "false";

            return PartialView(result);
        }
    }
}

SarvamCart/Controllers/ProductDetailController.cs
using SarvamCart.Domain.Data;
using SarvamCart.Domain.Models;
using SarvamCart.Domain.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SarvamCart.Controllers
{
    public class ProductDetailController : Controller
    {
        private readonly IProductService ProductService;
        //private readonly IProductImageService ManageProductImageServices;
        public ProductDetailController(IProductService _manageProductServices )
        {
            ProductService = _manageProductServices;
        }

        // GET: Product
        public ActionResult Index(int Id)
        {
            ManageProduct viewModel = new ManageProduct();

            var result = ProductService.FirstOrDefault(x => x.Id == Id && x.IsDeleted == false);
            if (result == null)
            {
                ViewBag.Message = "No Product";
            }
            else
            {
                viewModel.Id = result.Id;
                viewModel.Title = result.Title;
                viewModel.Stock = result.Stock;
                //viewModel.Image = result.Image;
                viewModel.IsActive = result.IsActive;
                viewModel.DisplayHome = result.DisplayHome;
                viewModel.Description = result.Description;
                viewModel.CategoryTypeId = result.CategoryTypeId;
                viewModel.Price = result.Price;
                viewModel.ProductCode = result.ProductCode;

                viewModel.CategoryType = result.CategoryType.CategoryName;

                viewModel.InnerImage=result.ProductImages?.Where(x=>x.IsDeleted==false).Select(x => new ManageProductImages { Id = x.Id, ProductId = x.ProductId, ImageName = x.InnerImages }).Take(5).ToList();
                viewModel.RelatedProduct = ProductService.FindBy(x => x.Id != result.Id && x.CategoryTypeId == result.CategoryTypeId && x.IsActive && x.IsDeleted==false).Take(12).ToList();
            }

            return View(viewModel);
        }
    }
}

SarvamCart/Views/Home/Index.cshtml
@model IEnumerable<SarvamCart.Domain.Models.ViewModelProduct>

@{
    ViewBag.Title = "Home Page";
}
<section>
    <div class="slider-main">
        <div id="carouselExampleFade" class="carousel slide carousel-fade" data-ride="carousel">
            <div class="carousel-inner">
                <div class="carousel-item active">
                    <div class="slider-bg">
                        <div class="container">
                            <div class="row align-items-center">
                                <div class="col-md-6 text-center text-md-left">
                                    <div class="slider-text">
                                        <h1>Unique Bottle <span>Umbrella.</span></h1>
                                        <p class="mb-0 text-center text-md-left">
                                            Let a smile be your umbrella, and you'll end up with a face full of rain.
                                        </p>
                                    </div>
                                </div>
                                <div class="col-md-6 order-first order-md-last">
                                    <img src="~/Assets/images/slider-img1.png" />
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="carousel-item">
                    <div class="slider-bg">
                        <div class="container">
                            <div class="row align-items-center">
                                <div class="col-md-6 text-center text-md-left">
                                    <div class="slider-text">
                                        <h1>All Type Lunch <span>Boxes.</span></h1>
                                        <p class="mb-0 text-center text-md-left">
                                            This lunch box is suitable for office, picnic, home, school and other places.
                                            Made of good quality acrylic material, durable for long lasting use.

                                        </p>
                                    </div>
                                </div>
                                <div class="col-md-6 order-first order-md-last">
                                    <img src="~/Assets/images/slider-img2.jpg" />
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <a class="carousel-control-prev" href="#carouselExampleFade" role="button" data-slide="prev">
                <div class="bordered">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                </div>
                <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carouselExampleFade" role="button" data-slide="next">
                <div class="bordered">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                </div>
                <span class="sr-only">Next</span>
            </a>
        </div>
    </div>
</section>
<section class="py--100 product-main">
    <div class="container">
        <div class="product-head">
            <h2 class="text-center"><span>FEW</span> PRODUCTS</h2>
        </div>
        <div class="row mt--50">

            @if (Model != null)
            {
                foreach (var item in Model)
                {
                    <div class="col-sm-6 col-md-4 col-lg-3 mb-3">
                        @*<a href="/Home/Product/@item.CategoryTypeId">*@
                        @*<a href="@Url.Action("Index", "ProductDetail", new { id = item.Id })">*@
                        <div class="product-box">
                            <img src="~/Assets/UploadedFiles/@item.InnerImage[0].InnerImages" alt="product" />
                            <div class="overlay">
                                <div class="wish-list-icon">
                                    <a href="#"><i class="fa fa-heart"></i></a>
                                    <a href="@Url.Action("Index", "ProductDetail", new { id = item.Id })"><i class="fa fa-info"></i></a>
                                    <a class="cartlnk" data-id="@item.Id"><i class="fa fa-shopping-cart"></i></a>
                                </div>
                            </div>
                        </div>
                        <p class="product-name text-center">@item.Title</p>
                        @* </a>*@
                    </div>
                }
            }
            <div class="col-12 text-center">
                <span class="no-items-message">@ViewBag.Message</span>
            </div>
        </div>

        @*<div class="product-btn text-center">
                <a href="@Url.Action("Product","Home")">View all</a>
            </div>*@
    </div>
</section>
<section>
    <div class="unique-product-main">
        <div class="container">
            <div class="row justify-content-center align-items-center">
                <div class="col-md-6 text-center">
                    <div id="carouselExampleFade" class="carousel slide carousel-fade" data-ride="carousel">
                        <div class="carousel-inner">
                            <div class="carousel-item active">
                                <img src="~/Assets/images/unique-product-img3.png" alt="First slide">
                            </div>
                            <div class="carousel-item">
                                <img src="~/Assets/images/unique-product-img2.png" alt="First slide">
                            </div>
                            <div class="carousel-item">
                                <img src="~/Assets/images/unique-product-img.png" alt="First slide">
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-sm-8 col-md-4">
                    <div class="unique-product-details">
                        <img src="~/Assets/images/review-star-img.png" alt="review-star" />
                        <p>
                            The Unique
                            Products.
                        </p>
                        <span>
                            So it's really for us about new products, because we have released a lot of new products.
                        </span>
                        @*<a class="unique-product-btn" href="#">View More</a>*@
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<section class="py--100">
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <a href="javascript:;">
                    <div class="image-section">
                        <div class="border-box"></div><p>Glassware</p>
                        <img src="~/Assets/images/img-section1.png" class="w-100" />
                    </div>
                </a>
            </div>
            <div class="col-md-6">
                <div class="row">
                    <div class="col-12 my-3 my-md-0">
                        <a href="javascript:;">
                            <div class="image-section">
                                <div class="border-box"></div><p>Kitchenware</p>
                                <img src="~/Assets/images/img-section2.png" class="w-100" />
                            </div>
                        </a>
                    </div>
                    <div class="col-12 mt--30">
                        <a href="javascript:;">
                            <div class="image-section">
                                <div class="border-box"></div><p>Wrist Watches</p>
                                <img src="~/Assets/images/img-section3.png" class="w-100" />
                            </div>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<section>
    <div class="offer">
        <div class="container">
            <div class="row">
                <div class="col-sm-6 col-xl-3">
                    <div class="row align-items-center justify-content-center">
                        <div class="col-3 col-sm-4 col-lg-3 col-xl-4">
                            <img src="~/Assets/images/free-delivery-icon.png" />
                        </div>
                        <div class="col-6 col-sm-8 pl-md-0">
                            <div class="offer-text">
                                <p>Fast Delivery</p>
                                <span>We Deliver 24 x 7</span>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-sm-6 col-xl-3">
                    <div class="row align-items-center my-3 my-sm-0 justify-content-center">
                        <div class="col-3 col-sm-4 col-lg-3 col-xl-4">
                            <img src="~/Assets/images/exchange-icon.png" />
                        </div>
                        <div class="col-6 col-sm-8 pl-md-0">
                            <div class="offer-text">
                                <p>FREE EXCHANGE</p>
                                <span>30 days return on all items.</span>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-sm-6 col-xl-3 mt-sm-3 mt-lg-0">
                    <div class="row align-items-center justify-content-center">
                        <div class="col-3 col-sm-4 col-lg-3 col-xl-4">
                            <img src="~/Assets/images/support-icon.png" />
                        </div>
                        <div class="col-6 col-sm-8 pl-md-0">
                            <div class="offer-text">
                                <p>PREMIUM SUPPORT</p>
                                <span>We support online 24 hours a day.</span>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-sm-6 col-xl-3 mt-sm-3 mt-lg-0">
                    <div class="row align-items-center my-3 my-sm-0 justify-content-center">
                        <div class="col-3 col-sm-4 col-lg-3 col-xl-4">
                            <img src="~/Assets/images/gift-icon.png" />
                        </div>
                        <div class="col-6 col-sm-8 pl-md-0">
                            <div class="offer-text">
                                <p>BLACK FRIDAY</p>
                                <span>Shocking discount every friday.</span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<section class="pt-100">
    <div class="toys-bg">
        <div class="container">
            <div class="row align-items-center justify-content-between">
                <div class="col-md-5">
                    <div class="toys-text">
                        <h2><span>Gym</span> Products.</h2>
                        <p class="pr-5">
                            We have products which emphasize on every individual's health.
                        </p>
                        @*<a href="@Url.Action("Product","Home")">View More</a>*@
                    </div>
                </div>
                <div class="col-md-5 text-right order-first order-md-last text-center">
                    <img src="~/Assets/images/toys-img.png" alt="toy" />
                </div>
            </div>
        </div>
    </div>
</section>

@section scripts{
    <script type="text/javascript">
        $(document).ready(function () {
            $(document).on("click", ".cartlnk", function () {
                var id = $(this).data('id');
                $.ajax({
                    type: "POST",
                    url: '@Url.Action("AddToCart", "UserCart")',
                    data: { productId: id },
                    success: function (result) {
                        if (result.IsSuccess == true) {
                            location.reload();
                        }
                        else {
                            window.location.href = "@Url.Action("Login", "Account")";
                        }
                    }

                });
            });
        });

          $(function(){
             var msg = "@(TempData["Msg"] as string)";
             if (msg !== "") {
                 toastr.success(msg);
             }
         });


    </script>
}