SarvamCart/Controllers/QuotationHistoryController.cs
using Rotativa;
using Rotativa.Options;
using SarvamCart.Domain.Models;
using SarvamCart.Domain.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SarvamCart.Controllers
{
    public class QuotationHistoryController : Controller
    {
        private readonly IQuotationService QuotationService;
        private readonly IQuotationDetailService QuotationDetailService;
        private readonly IProductImageService ProductImageService;
        private readonly Models.UserManager UserManager;

        public QuotationHistoryController(IQuotationService _quotationServices, UserService _userservice, IQuotationDetailService _quotationDetailService, IProductImageService _ProductImageService, Models.UserManager _userManager)
        {
            QuotationService = _quotationServices;
            UserManager = _userManager;
            ProductImageService = _ProductImageService;
            QuotationDetailService = _quotationDetailService;
        }
        // GET: OrderHistory
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult QuotationHistory(int? userId)
        {
            userId = UserManager.UserDetail.UserID;
            ViewBag.Quotations = QuotationService.FindBy(x => x.UserId == userId && (x.StatusOfOrder==1 || x.StatusOfOrder == 2)).ToList();
            ViewBag.QuotationsCount = QuotationService.FindBy(x => x.UserId == userId && (x.StatusOfOrder==1 || x.StatusOfOrder == 2)).Count();

            if (userId>0)
            {
                ViewModelQuotaion viewModel = new ViewModelQuotaion();
                
            }

            return View();
        }
        //public ActionResult QuotationDetails(int? id)
        //{
        //    var quotation = QuotationService.FirstOrDefault(x => x.Id == id);

        //    ViewModelQuotaion viewModel = new ViewModelQuotaion();
        //    if (id > 0)
        //    {
        //        viewModel.UserName = quotation.User.UserName;
        //        viewModel.UserEmail = quotation.User.EmailAddress;
        //        viewModel.ContactNumber = quotation.User.ContactNumber;
        //        viewModel.CreatedOn = (DateTime)quotation.CreatedOn;
        //        viewModel.GrantTotal = quotation.GrantTotal ??0;

        //        viewModel.CartDetails = quotation.QuotationDetails.Select(x => new ManageQuotaionDetailModel
        //        {
        //            Id = x.Id,
        //            QuotationId = x.QuotationId ?? 0,
        //            ProductId = x.ProductId ?? 0,
        //            ProductName = x.Product.Title,
        //            ProductCode = x.Product.ProductCode,
        //            FinalPrice = x.FinalPrice ?? 0,
        //            Quentity = Convert.ToInt32(x.Quentity ?? 0),
        //            ProductImage = ProductImageService.FirstOrDefault(p => p.ProductId == x.ProductId && !p.IsDeleted).InnerImages
        //        }).ToList();
        //    }
        //    return View(viewModel);
        //}

        public ActionResult QuotationDetails(int? id)
        {
           
            var quotation = QuotationService.FirstOrDefault(x => x.Id == id);

            ViewModelQuotaion viewModel = new ViewModelQuotaion();
            if (id > 0)
            {
                viewModel.UserName = quotation.User.UserName;
                viewModel.UserEmail = quotation.User.EmailAddress;
                viewModel.ContactNumber = quotation.User.ContactNumber;
                viewModel.CreatedOn = (DateTime)quotation.CreatedOn;
                viewModel.GrantTotal = quotation.GrantTotal ?? 0;
                viewModel.Id = quotation.Id;

                viewModel.CartDetails = quotation.QuotationDetails.Select(x => new ManageQuotaionDetailModel
                {
                    Id = x.Id,
                    QuotationId = x.QuotationId ?? 0,
                    ProductId = x.ProductId ?? 0,
                    ProductName = x.Product.Title,
                    ProductCode = x.Product.ProductCode,
                    FinalPrice = x.FinalPrice ?? 0,
                    Quentity = Convert.ToInt32(x.Quentity ?? 0),
                    ProductImage = ProductImageService.FirstOrDefault(p => p.ProductId == x.ProductId && !p.IsDeleted).InnerImages
                }).ToList();
            }
            return View(viewModel);
        }

        public ActionResult _QuotationPdf(int? id)
        {
            var quotation = QuotationService.FirstOrDefault(x => x.Id == id);

            ViewModelQuotaion viewModel = new ViewModelQuotaion();
            if (id > 0)
            {
                viewModel.UserName = quotation.User.UserName;
                viewModel.UserEmail = quotation.User.EmailAddress;
                viewModel.ContactNumber = quotation.User.ContactNumber;
                viewModel.CreatedOn = (DateTime)quotation.CreatedOn;
                viewModel.GrantTotal = quotation.GrantTotal ?? 0;

                viewModel.CartDetails = quotation.QuotationDetails.Select(x => new ManageQuotaionDetailModel
                {
                    Id = x.Id,
                    QuotationId = x.QuotationId ?? 0,
                    ProductId = x.ProductId ?? 0,
                    ProductName = x.Product.Title,
                    ProductCode = x.Product.ProductCode,
                    FinalPrice = x.FinalPrice ?? 0,
                    Quentity = Convert.ToInt32(x.Quentity ?? 0),
                    ProductImage = ProductImageService.FirstOrDefault(p => p.ProductId == x.ProductId && !p.IsDeleted).InnerImages
                }).ToList();
            }

            return PartialView(viewModel);
        }

        public ActionResult DownloadPdf(int? id)
        {
            return new ActionAsPdf("_QuotationPdf",new { id=id}) { FileName = "Quotation.pdf" , PageSize = Size.A4 };
            //return new ActionAsImage("_Test"){ FileName = "test.pdf"  };
        }

    }
}

SarvamCart/Views/QuotationHistory/QuotationDetails.cshtml
@model SarvamCart.Domain.Models.ViewModelQuotaion
@{
    ViewBag.Title = "Quotation Details";
}
@Html.HiddenFor(x => Model.Id);
@Html.HiddenFor(x => Model.UserId);

<section>
    <div class="sub-page-slider">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-6">
                    <div class="sub-page-head">
                        <h1>Your <span>Quotation Detail</span></h1>
                        @*<p>Know about us more</p>*@
                    </div>
                </div>
                <div class="col-6 text-right">
                    <nav aria-label="breadcrumb" class="d-inline-block">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="@Url.Action("Index", "Home")">Home</a></li>
                            <li class="breadcrumb-item active"> Quotation Detail</li>
                        </ol>
                    </nav>
                </div>
            </div>
        </div>
    </div>
</section>
<section>

    @{Html.RenderAction("_QuotationPdf", "QuotationHistory",new { id=Model.Id}); }

    <div class="text-center">
        <a href="@Url.Action("DownloadPdf","QuotationHistory",new { id=Model.Id})">Download Pdf</a>
        @*<button id="cmd" type="button" class="pdf-btn"><i class="fa fa-download"></i> Download PDF</button>*@
        @*<button type="button" class="pdf-btn" onclick="window.location.href('@Url.Action("DownloadPdf","QuotationHistory")')"><i class="fa fa-download"></i> Download PDF</button>*@
    </div>
</section>
@*@section scripts{
        <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.22/pdfmake.min.js"></script>
        <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/html2canvas/0.4.1/html2canvas.min.js"></script>

        <script type="text/javascript">
            //convert quotation in pdf format

            $("body").on("click", "#cmd", function () {
                $(".updtPrice").show();
                $(".finalPrice").hide();
                html2canvas($('#content')[0], {
                    onrendered: function (canvas) {
                        var data = canvas.toDataURL();
                        var docDefinition = {
                            content: [{
                                image: data,
                                width: 580,
                                fontsize: 18
                            }]
                        };
                        pdfMake.createPdf(docDefinition).download("Quotation.pdf");
                    }
                });
            });
        </script>
    }*@

SarvamCart/Views/QuotationHistory/QuotationHistory.cshtml
@model SarvamCart.Domain.Models.ViewModelQuotaion
@{
    ViewBag.Title = "QuotationHistory";
}
<section>
    <div class="sub-page-slider">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-6">
                    <div class="sub-page-head">
                        <h1>Your <span>Quotation History</span></h1>
                        @*<p>Know about us more</p>*@
                    </div>
                </div>
                <div class="col-6 text-right">
                    <nav aria-label="breadcrumb" class="d-inline-block">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="@Url.Action("Index", "Home")">Home</a></li>
                            <li class="breadcrumb-item active"> Quotation History</li>
                        </ol>
                    </nav>
                </div>
            </div>
        </div>
    </div>
</section>

<section>
    <div class="container">
        <div class="order-list">
            <div class="table-responsive">
                <h3>Quotation History<span>(@ViewBag.QuotationsCount)</span></h3>
                <table>
                    <tr>
                        <th>Date</th>
                        <th>Status</th>
                        <th>Total Amount</th>
                        <th>View Details</th>
                    </tr>
                    @if (ViewBag.Quotations != null)
                    {
                        foreach (var quotation in ViewBag.Quotations)
                        {
                            <tr>
                                <td> <p>@quotation.CreatedOn.ToString("dd/MM/yyyy")</p></td>
                                <td>
                                    @if (quotation.StatusOfOrder == 1)
                                    {
                                        <h2>
                                            Pending
                                        </h2>
                                    }
                                    else
                                    {
                                        <h2>
                                            Done
                                        </h2>
                                    }
                                </td>
                                <td>
                                    @if (@quotation.GrantTotal == null)
                                    {
                                        <p>-</p>
                                    }
                                    else
                                    {
                                        <p>@quotation.GrantTotal /-</p>

                                    }
                                </td>
                                <td>
                                    @if (quotation.StatusOfOrder == 1)
                                    {
                                        <p>-</p>
                                    }
                                    else
                                    {
                                        <a href="@Url.Action("QuotationDetails", "QuotationHistory", new { id = quotation.Id })">View Detail</a>
                                    }
                                </td>
                            </tr>
                        }
                    }
                </table>
            </div>
        </div>
    </div>
</section>